log-level: error
parameters:
  - ingest:
      ...
    name: ingest_collector
  - decode:
      ...
    name: decode_json

  - name: transform_generic
    transform:
      generic:
        ...
      type: generic

  - name: transform_network
    transform:
      network:
        ...
      type: network

  - name: connection_tracking
    conn_track: # Or connTrack/connectionTracking/connection_tracking

      finishTimeouts: # Per protocol. What if protocol is not one of key fields?
        tcp: 2m
        udp: 30s
        default: 5m

      updateInterval: 1m
      updateFlowLogsCount: 100

      # TODO: Add config option to set the field of the hash
      outputRecordTypes:
        - start # newConnection
        - updates # updatedConnection
        - end # finishedConnection
        # The input fields should include the hash of the connection
        - input # flows/originalFlowLogs


      # All the key fields, along with the hash of the connection will be outputted as well.
      keyFields:
        fieldsGroup:
          - name: src
            fields:
              - src_ip
              - src_port
              - InIf
          - name: dst
            fields:
              - dst_ip
              - dst_port
              - OutIf
          - name: protocol
            fields:
              - protocol_field
        hash:
          fieldGroups:
            - protocol
          fieldGroupPair:
            keyA: dst
            keyB: src


      # In case of two-way, each tracking field must be duplicated one for src->dst and one for dst->src.
      # What prefix/suffix to use?
      # Do we really want this complication?
      # I guess summing bytes from the two directions makes no sense.
      outputFields:
        - name: bytes
          operation: sum
          # think of a different name for bidi
          bidi: true # default: false
        - name: packets
          operation: sum
        # Number of flows in a connection
        # The following is confusing because it says "count bytes"
        - name: numFlowLogEntries # This could be any field in the flow log
          operation: count
          # If the operation is `count` we don't need an 'input' field
          # add an example for input in a different field
          input: bytes # if input is not specified, it's set the same as "name"
        - name: startTime
          operation: min
        - name: endTime
          operation: max

  - name: extract_aggregate
    extract:
      aggregates:
        ...
      type: aggregates

  - name: encode_prom
    encode:
      prom:
        ...
      type: prom


  - name: write_none
    write:
      ...

pipeline:
  - name: ingest_collector
  - follows: ingest_collector
    name: decode_json
  - follows: decode_json
    name: transform_generic
  - follows: transform_generic
    name: transform_network

  - follows: transform_network
    name: connection_tracking

  - follows: connection_tracking
    name: encode_prom

  - follows: extract_aggregate
    name: encode_prom
  - follows: encode_prom
    name: write_none

