apiVersion: v1
kind: Pod
metadata:
  name: flp-ipfix-stdout
  labels:
    app: flp-ipfix-stdout
spec:
  containers:
    - name: flp-ipfix-stdout
      image: quay.io/jotak/flowlogs-pipeline:main
      imagePullPolicy: Always
      args:
      - "--config=/etc/flowlogs-pipeline/config.yaml"
      ports:
        - containerPort: 2055
      volumeMounts:
        - name: configuration
          mountPath: "/etc/flowlogs-pipeline/"
  volumes:
    - name: configuration
      configMap:
        name: flp-ipfix-stdout-config
---
apiVersion: v1
kind: Service
metadata:
  name: flp-ipfix-stdout
  labels:
    app: flp-ipfix-stdout
spec:
  ports:
    - port: 2055
      targetPort: 2055
      protocol: UDP
      name: ipfix
  selector:
    app: flp-ipfix-stdout
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: flp-ipfix-stdout-config
data:
  config.yaml: |
    log-level: info
    pipeline:
      - name: ingest
      - name: write
        follows: ingest
    parameters:
      - name: ingest
        ingest:
          type: ipfix
          ipfix:
            port: 2055
            mapping:
              - penprovided: true
                pen: 2
                field: 7733
                destination: CustomBytes_1
              - penprovided: true
                pen: 2
                field: 7734
                destination: CustomBytes_2
              - penprovided: true
                pen: 2
                field: 7735
                destination: CustomBytes_3
              - penprovided: true
                pen: 2
                field: 7736
                destination: CustomBytes_4
      - name: write
        write:
          type: stdout
