// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: proto/genericmap.proto

package genericmap

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request message containing the GenericMap
type Flow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GenericMap    *anypb.Any             `protobuf:"bytes,1,opt,name=genericMap,proto3" json:"genericMap,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Flow) Reset() {
	*x = Flow{}
	mi := &file_proto_genericmap_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Flow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Flow) ProtoMessage() {}

func (x *Flow) ProtoReflect() protoreflect.Message {
	mi := &file_proto_genericmap_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Flow.ProtoReflect.Descriptor instead.
func (*Flow) Descriptor() ([]byte, []int) {
	return file_proto_genericmap_proto_rawDescGZIP(), []int{0}
}

func (x *Flow) GetGenericMap() *anypb.Any {
	if x != nil {
		return x.GenericMap
	}
	return nil
}

// intentionally empty
type CollectorReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectorReply) Reset() {
	*x = CollectorReply{}
	mi := &file_proto_genericmap_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectorReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectorReply) ProtoMessage() {}

func (x *CollectorReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_genericmap_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectorReply.ProtoReflect.Descriptor instead.
func (*CollectorReply) Descriptor() ([]byte, []int) {
	return file_proto_genericmap_proto_rawDescGZIP(), []int{1}
}

var File_proto_genericmap_proto protoreflect.FileDescriptor

const file_proto_genericmap_proto_rawDesc = "" +
	"\n" +
	"\x16proto/genericmap.proto\x12\n" +
	"genericmap\x1a\x19google/protobuf/any.proto\"<\n" +
	"\x04Flow\x124\n" +
	"\n" +
	"genericMap\x18\x01 \x01(\v2\x14.google.protobuf.AnyR\n" +
	"genericMap\"\x10\n" +
	"\x0eCollectorReply2C\n" +
	"\tCollector\x126\n" +
	"\x04Send\x12\x10.genericmap.Flow\x1a\x1a.genericmap.CollectorReply\"\x00B\x0eZ\f./genericmapb\x06proto3"

var (
	file_proto_genericmap_proto_rawDescOnce sync.Once
	file_proto_genericmap_proto_rawDescData []byte
)

func file_proto_genericmap_proto_rawDescGZIP() []byte {
	file_proto_genericmap_proto_rawDescOnce.Do(func() {
		file_proto_genericmap_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_genericmap_proto_rawDesc), len(file_proto_genericmap_proto_rawDesc)))
	})
	return file_proto_genericmap_proto_rawDescData
}

var file_proto_genericmap_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_genericmap_proto_goTypes = []any{
	(*Flow)(nil),           // 0: genericmap.Flow
	(*CollectorReply)(nil), // 1: genericmap.CollectorReply
	(*anypb.Any)(nil),      // 2: google.protobuf.Any
}
var file_proto_genericmap_proto_depIdxs = []int32{
	2, // 0: genericmap.Flow.genericMap:type_name -> google.protobuf.Any
	0, // 1: genericmap.Collector.Send:input_type -> genericmap.Flow
	1, // 2: genericmap.Collector.Send:output_type -> genericmap.CollectorReply
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_genericmap_proto_init() }
func file_proto_genericmap_proto_init() {
	if File_proto_genericmap_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_genericmap_proto_rawDesc), len(file_proto_genericmap_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_genericmap_proto_goTypes,
		DependencyIndexes: file_proto_genericmap_proto_depIdxs,
		MessageInfos:      file_proto_genericmap_proto_msgTypes,
	}.Build()
	File_proto_genericmap_proto = out.File
	file_proto_genericmap_proto_goTypes = nil
	file_proto_genericmap_proto_depIdxs = nil
}
