log-level: info
pipeline:
  - name: ingest
  - name: enrich
    follows: ingest
  - name: write_ipfix
    follows: enrich
parameters:
  - name: ingest
    ingest:
      type: grpc
      grpc:
        port: 9999
  - name: enrich
    transform:
      type: network
      network:
        rules:
          - input: SrcAddr
            output: SrcK8S
            type: "add_kubernetes"
          - input: DstAddr
            output: DstK8S
            type: "add_kubernetes"
  - name: write_ipfix
    write:
      type: ipfix
      ipfix:
        targetHost: 127.0.0.1
        targetPort: 9998
        transport: tcp
        enterpriseID: 27207

