// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: proto/k8scache.proto

package k8scache

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// OperationType defines the kind of cache operation
type OperationType int32

const (
	OperationType_OPERATION_UNSPECIFIED OperationType = 0
	OperationType_OPERATION_ADD         OperationType = 1
	OperationType_OPERATION_UPDATE      OperationType = 2
	OperationType_OPERATION_DELETE      OperationType = 3
)

// Enum value maps for OperationType.
var (
	OperationType_name = map[int32]string{
		0: "OPERATION_UNSPECIFIED",
		1: "OPERATION_ADD",
		2: "OPERATION_UPDATE",
		3: "OPERATION_DELETE",
	}
	OperationType_value = map[string]int32{
		"OPERATION_UNSPECIFIED": 0,
		"OPERATION_ADD":         1,
		"OPERATION_UPDATE":      2,
		"OPERATION_DELETE":      3,
	}
)

func (x OperationType) Enum() *OperationType {
	p := new(OperationType)
	*p = x
	return p
}

func (x OperationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OperationType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_k8scache_proto_enumTypes[0].Descriptor()
}

func (OperationType) Type() protoreflect.EnumType {
	return &file_proto_k8scache_proto_enumTypes[0]
}

func (x OperationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OperationType.Descriptor instead.
func (OperationType) EnumDescriptor() ([]byte, []int) {
	return file_proto_k8scache_proto_rawDescGZIP(), []int{0}
}

// SyncMessage is sent by FLP processors (server) to the informers (client)
type SyncMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*SyncMessage_Request
	//	*SyncMessage_Ack
	Message       isSyncMessage_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncMessage) Reset() {
	*x = SyncMessage{}
	mi := &file_proto_k8scache_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncMessage) ProtoMessage() {}

func (x *SyncMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_k8scache_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncMessage.ProtoReflect.Descriptor instead.
func (*SyncMessage) Descriptor() ([]byte, []int) {
	return file_proto_k8scache_proto_rawDescGZIP(), []int{0}
}

func (x *SyncMessage) GetMessage() isSyncMessage_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *SyncMessage) GetRequest() *SyncRequest {
	if x != nil {
		if x, ok := x.Message.(*SyncMessage_Request); ok {
			return x.Request
		}
	}
	return nil
}

func (x *SyncMessage) GetAck() *SyncAck {
	if x != nil {
		if x, ok := x.Message.(*SyncMessage_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

type isSyncMessage_Message interface {
	isSyncMessage_Message()
}

type SyncMessage_Request struct {
	Request *SyncRequest `protobuf:"bytes,1,opt,name=request,proto3,oneof"`
}

type SyncMessage_Ack struct {
	Ack *SyncAck `protobuf:"bytes,2,opt,name=ack,proto3,oneof"`
}

func (*SyncMessage_Request) isSyncMessage_Message() {}

func (*SyncMessage_Ack) isSyncMessage_Message() {}

// SyncRequest is sent when an FLP processor connects or reconnects
type SyncRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProcessorId   string                 `protobuf:"bytes,1,opt,name=processor_id,json=processorId,proto3" json:"processor_id,omitempty"`  // Unique identifier for the FLP processor pod
	LastVersion   int64                  `protobuf:"varint,2,opt,name=last_version,json=lastVersion,proto3" json:"last_version,omitempty"` // Last cache version seen (0 if requesting full snapshot)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncRequest) Reset() {
	*x = SyncRequest{}
	mi := &file_proto_k8scache_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRequest) ProtoMessage() {}

func (x *SyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_k8scache_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncRequest.ProtoReflect.Descriptor instead.
func (*SyncRequest) Descriptor() ([]byte, []int) {
	return file_proto_k8scache_proto_rawDescGZIP(), []int{1}
}

func (x *SyncRequest) GetProcessorId() string {
	if x != nil {
		return x.ProcessorId
	}
	return ""
}

func (x *SyncRequest) GetLastVersion() int64 {
	if x != nil {
		return x.LastVersion
	}
	return 0
}

// SyncAck acknowledges receipt of cache updates
type SyncAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProcessorId   string                 `protobuf:"bytes,1,opt,name=processor_id,json=processorId,proto3" json:"processor_id,omitempty"`
	Version       int64                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"` // The version that was successfully applied
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"` // Whether the update was applied successfully
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`      // Error message if success = false
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncAck) Reset() {
	*x = SyncAck{}
	mi := &file_proto_k8scache_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncAck) ProtoMessage() {}

func (x *SyncAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_k8scache_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncAck.ProtoReflect.Descriptor instead.
func (*SyncAck) Descriptor() ([]byte, []int) {
	return file_proto_k8scache_proto_rawDescGZIP(), []int{2}
}

func (x *SyncAck) GetProcessorId() string {
	if x != nil {
		return x.ProcessorId
	}
	return ""
}

func (x *SyncAck) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *SyncAck) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SyncAck) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// CacheUpdate represents an incremental change to the cache
type CacheUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       int64                  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`                         // Monotonically increasing version number
	IsSnapshot    bool                   `protobuf:"varint,2,opt,name=is_snapshot,json=isSnapshot,proto3" json:"is_snapshot,omitempty"` // True if this is a full snapshot, false for incremental
	Entries       []*ResourceEntry       `protobuf:"bytes,3,rep,name=entries,proto3" json:"entries,omitempty"`
	Operation     OperationType          `protobuf:"varint,4,opt,name=operation,proto3,enum=k8scache.OperationType" json:"operation,omitempty"` // Only relevant when is_snapshot = false
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CacheUpdate) Reset() {
	*x = CacheUpdate{}
	mi := &file_proto_k8scache_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CacheUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheUpdate) ProtoMessage() {}

func (x *CacheUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_k8scache_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheUpdate.ProtoReflect.Descriptor instead.
func (*CacheUpdate) Descriptor() ([]byte, []int) {
	return file_proto_k8scache_proto_rawDescGZIP(), []int{3}
}

func (x *CacheUpdate) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *CacheUpdate) GetIsSnapshot() bool {
	if x != nil {
		return x.IsSnapshot
	}
	return false
}

func (x *CacheUpdate) GetEntries() []*ResourceEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *CacheUpdate) GetOperation() OperationType {
	if x != nil {
		return x.Operation
	}
	return OperationType_OPERATION_UNSPECIFIED
}

// ResourceEntry represents a single Kubernetes resource in the cache
type ResourceEntry struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Kind      string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"` // "Pod", "Node", or "Service"
	Namespace string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name      string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Uid       string                 `protobuf:"bytes,4,opt,name=uid,proto3" json:"uid,omitempty"`
	// Resource-specific metadata
	OwnerName        string            `protobuf:"bytes,5,opt,name=owner_name,json=ownerName,proto3" json:"owner_name,omitempty"`
	OwnerKind        string            `protobuf:"bytes,6,opt,name=owner_kind,json=ownerKind,proto3" json:"owner_kind,omitempty"`
	HostName         string            `protobuf:"bytes,7,opt,name=host_name,json=hostName,proto3" json:"host_name,omitempty"`                            // For Pods: the node name
	HostIp           string            `protobuf:"bytes,8,opt,name=host_ip,json=hostIp,proto3" json:"host_ip,omitempty"`                                  // For Pods: the node IP
	NetworkName      string            `protobuf:"bytes,9,opt,name=network_name,json=networkName,proto3" json:"network_name,omitempty"`                   // For multi-network support
	Ips              []string          `protobuf:"bytes,10,rep,name=ips,proto3" json:"ips,omitempty"`                                                     // IP addresses associated with this resource
	SecondaryNetKeys []string          `protobuf:"bytes,11,rep,name=secondary_net_keys,json=secondaryNetKeys,proto3" json:"secondary_net_keys,omitempty"` // Secondary network keys for CNI plugins
	Labels           map[string]string `protobuf:"bytes,12,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Annotations      map[string]string `protobuf:"bytes,13,rep,name=annotations,proto3" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Kubernetes metadata
	CreationTimestamp int64  `protobuf:"varint,14,opt,name=creation_timestamp,json=creationTimestamp,proto3" json:"creation_timestamp,omitempty"` // Unix timestamp
	ResourceVersion   string `protobuf:"bytes,15,opt,name=resource_version,json=resourceVersion,proto3" json:"resource_version,omitempty"`        // K8s resource version
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ResourceEntry) Reset() {
	*x = ResourceEntry{}
	mi := &file_proto_k8scache_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceEntry) ProtoMessage() {}

func (x *ResourceEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_k8scache_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceEntry.ProtoReflect.Descriptor instead.
func (*ResourceEntry) Descriptor() ([]byte, []int) {
	return file_proto_k8scache_proto_rawDescGZIP(), []int{4}
}

func (x *ResourceEntry) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ResourceEntry) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ResourceEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResourceEntry) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *ResourceEntry) GetOwnerName() string {
	if x != nil {
		return x.OwnerName
	}
	return ""
}

func (x *ResourceEntry) GetOwnerKind() string {
	if x != nil {
		return x.OwnerKind
	}
	return ""
}

func (x *ResourceEntry) GetHostName() string {
	if x != nil {
		return x.HostName
	}
	return ""
}

func (x *ResourceEntry) GetHostIp() string {
	if x != nil {
		return x.HostIp
	}
	return ""
}

func (x *ResourceEntry) GetNetworkName() string {
	if x != nil {
		return x.NetworkName
	}
	return ""
}

func (x *ResourceEntry) GetIps() []string {
	if x != nil {
		return x.Ips
	}
	return nil
}

func (x *ResourceEntry) GetSecondaryNetKeys() []string {
	if x != nil {
		return x.SecondaryNetKeys
	}
	return nil
}

func (x *ResourceEntry) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *ResourceEntry) GetAnnotations() map[string]string {
	if x != nil {
		return x.Annotations
	}
	return nil
}

func (x *ResourceEntry) GetCreationTimestamp() int64 {
	if x != nil {
		return x.CreationTimestamp
	}
	return 0
}

func (x *ResourceEntry) GetResourceVersion() string {
	if x != nil {
		return x.ResourceVersion
	}
	return ""
}

var File_proto_k8scache_proto protoreflect.FileDescriptor

const file_proto_k8scache_proto_rawDesc = "" +
	"\n" +
	"\x14proto/k8scache.proto\x12\bk8scache\"r\n" +
	"\vSyncMessage\x121\n" +
	"\arequest\x18\x01 \x01(\v2\x15.k8scache.SyncRequestH\x00R\arequest\x12%\n" +
	"\x03ack\x18\x02 \x01(\v2\x11.k8scache.SyncAckH\x00R\x03ackB\t\n" +
	"\amessage\"S\n" +
	"\vSyncRequest\x12!\n" +
	"\fprocessor_id\x18\x01 \x01(\tR\vprocessorId\x12!\n" +
	"\flast_version\x18\x02 \x01(\x03R\vlastVersion\"v\n" +
	"\aSyncAck\x12!\n" +
	"\fprocessor_id\x18\x01 \x01(\tR\vprocessorId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x03R\aversion\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"\xb2\x01\n" +
	"\vCacheUpdate\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x03R\aversion\x12\x1f\n" +
	"\vis_snapshot\x18\x02 \x01(\bR\n" +
	"isSnapshot\x121\n" +
	"\aentries\x18\x03 \x03(\v2\x17.k8scache.ResourceEntryR\aentries\x125\n" +
	"\toperation\x18\x04 \x01(\x0e2\x17.k8scache.OperationTypeR\toperation\"\x9c\x05\n" +
	"\rResourceEntry\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x10\n" +
	"\x03uid\x18\x04 \x01(\tR\x03uid\x12\x1d\n" +
	"\n" +
	"owner_name\x18\x05 \x01(\tR\townerName\x12\x1d\n" +
	"\n" +
	"owner_kind\x18\x06 \x01(\tR\townerKind\x12\x1b\n" +
	"\thost_name\x18\a \x01(\tR\bhostName\x12\x17\n" +
	"\ahost_ip\x18\b \x01(\tR\x06hostIp\x12!\n" +
	"\fnetwork_name\x18\t \x01(\tR\vnetworkName\x12\x10\n" +
	"\x03ips\x18\n" +
	" \x03(\tR\x03ips\x12,\n" +
	"\x12secondary_net_keys\x18\v \x03(\tR\x10secondaryNetKeys\x12;\n" +
	"\x06labels\x18\f \x03(\v2#.k8scache.ResourceEntry.LabelsEntryR\x06labels\x12J\n" +
	"\vannotations\x18\r \x03(\v2(.k8scache.ResourceEntry.AnnotationsEntryR\vannotations\x12-\n" +
	"\x12creation_timestamp\x18\x0e \x01(\x03R\x11creationTimestamp\x12)\n" +
	"\x10resource_version\x18\x0f \x01(\tR\x0fresourceVersion\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a>\n" +
	"\x10AnnotationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*i\n" +
	"\rOperationType\x12\x19\n" +
	"\x15OPERATION_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rOPERATION_ADD\x10\x01\x12\x14\n" +
	"\x10OPERATION_UPDATE\x10\x02\x12\x14\n" +
	"\x10OPERATION_DELETE\x10\x032]\n" +
	"\x16KubernetesCacheService\x12C\n" +
	"\rStreamUpdates\x12\x15.k8scache.CacheUpdate\x1a\x15.k8scache.SyncMessage\"\x00(\x010\x01B\fZ\n" +
	"./k8scacheb\x06proto3"

var (
	file_proto_k8scache_proto_rawDescOnce sync.Once
	file_proto_k8scache_proto_rawDescData []byte
)

func file_proto_k8scache_proto_rawDescGZIP() []byte {
	file_proto_k8scache_proto_rawDescOnce.Do(func() {
		file_proto_k8scache_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_k8scache_proto_rawDesc), len(file_proto_k8scache_proto_rawDesc)))
	})
	return file_proto_k8scache_proto_rawDescData
}

var file_proto_k8scache_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_k8scache_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_k8scache_proto_goTypes = []any{
	(OperationType)(0),    // 0: k8scache.OperationType
	(*SyncMessage)(nil),   // 1: k8scache.SyncMessage
	(*SyncRequest)(nil),   // 2: k8scache.SyncRequest
	(*SyncAck)(nil),       // 3: k8scache.SyncAck
	(*CacheUpdate)(nil),   // 4: k8scache.CacheUpdate
	(*ResourceEntry)(nil), // 5: k8scache.ResourceEntry
	nil,                   // 6: k8scache.ResourceEntry.LabelsEntry
	nil,                   // 7: k8scache.ResourceEntry.AnnotationsEntry
}
var file_proto_k8scache_proto_depIdxs = []int32{
	2, // 0: k8scache.SyncMessage.request:type_name -> k8scache.SyncRequest
	3, // 1: k8scache.SyncMessage.ack:type_name -> k8scache.SyncAck
	5, // 2: k8scache.CacheUpdate.entries:type_name -> k8scache.ResourceEntry
	0, // 3: k8scache.CacheUpdate.operation:type_name -> k8scache.OperationType
	6, // 4: k8scache.ResourceEntry.labels:type_name -> k8scache.ResourceEntry.LabelsEntry
	7, // 5: k8scache.ResourceEntry.annotations:type_name -> k8scache.ResourceEntry.AnnotationsEntry
	4, // 6: k8scache.KubernetesCacheService.StreamUpdates:input_type -> k8scache.CacheUpdate
	1, // 7: k8scache.KubernetesCacheService.StreamUpdates:output_type -> k8scache.SyncMessage
	7, // [7:8] is the sub-list for method output_type
	6, // [6:7] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_proto_k8scache_proto_init() }
func file_proto_k8scache_proto_init() {
	if File_proto_k8scache_proto != nil {
		return
	}
	file_proto_k8scache_proto_msgTypes[0].OneofWrappers = []any{
		(*SyncMessage_Request)(nil),
		(*SyncMessage_Ack)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_k8scache_proto_rawDesc), len(file_proto_k8scache_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_k8scache_proto_goTypes,
		DependencyIndexes: file_proto_k8scache_proto_depIdxs,
		EnumInfos:         file_proto_k8scache_proto_enumTypes,
		MessageInfos:      file_proto_k8scache_proto_msgTypes,
	}.Build()
	File_proto_k8scache_proto = out.File
	file_proto_k8scache_proto_goTypes = nil
	file_proto_k8scache_proto_depIdxs = nil
}
