// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.19.6
// source: proto/k8scache.proto

package k8scache

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	KubernetesCacheService_StreamUpdates_FullMethodName = "/k8scache.KubernetesCacheService/StreamUpdates"
)

// KubernetesCacheServiceClient is the client API for KubernetesCacheService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// KubernetesCacheService defines the bidirectional streaming service for cache synchronization
// between the centralized informers pod and the distributed FLP processor pods.
//
// Flow:
// 1. FLP processor (server) accepts connection from informers (client)
// 2. FLP sends SyncRequest indicating what version it has
// 3. Informers sends CacheUpdate (snapshot or incremental)
// 4. FLP sends SyncAck to confirm receipt
// 5. Repeat steps 3-4 for ongoing updates
type KubernetesCacheServiceClient interface {
	// StreamUpdates establishes a bidirectional stream:
	// - Informers (client) send CacheUpdate messages (snapshots and incremental updates)
	// - FLP processors (server) send SyncRequest and SyncAck messages
	//
	// NOTE: In protobuf syntax, "rpc Method(stream A) returns (stream B)":
	//   - A = what server RECEIVES (what client SENDS)
	//   - B = what server SENDS (what client RECEIVES)
	//
	// We want:
	//   - Server receives: CacheUpdate (from informers client)
	//   - Server sends: SyncMessage (requests/acks)
	//
	// Therefore we need: (stream CacheUpdate) returns (stream SyncMessage)
	StreamUpdates(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[CacheUpdate, SyncMessage], error)
}

type kubernetesCacheServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewKubernetesCacheServiceClient(cc grpc.ClientConnInterface) KubernetesCacheServiceClient {
	return &kubernetesCacheServiceClient{cc}
}

func (c *kubernetesCacheServiceClient) StreamUpdates(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[CacheUpdate, SyncMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &KubernetesCacheService_ServiceDesc.Streams[0], KubernetesCacheService_StreamUpdates_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CacheUpdate, SyncMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type KubernetesCacheService_StreamUpdatesClient = grpc.BidiStreamingClient[CacheUpdate, SyncMessage]

// KubernetesCacheServiceServer is the server API for KubernetesCacheService service.
// All implementations must embed UnimplementedKubernetesCacheServiceServer
// for forward compatibility.
//
// KubernetesCacheService defines the bidirectional streaming service for cache synchronization
// between the centralized informers pod and the distributed FLP processor pods.
//
// Flow:
// 1. FLP processor (server) accepts connection from informers (client)
// 2. FLP sends SyncRequest indicating what version it has
// 3. Informers sends CacheUpdate (snapshot or incremental)
// 4. FLP sends SyncAck to confirm receipt
// 5. Repeat steps 3-4 for ongoing updates
type KubernetesCacheServiceServer interface {
	// StreamUpdates establishes a bidirectional stream:
	// - Informers (client) send CacheUpdate messages (snapshots and incremental updates)
	// - FLP processors (server) send SyncRequest and SyncAck messages
	//
	// NOTE: In protobuf syntax, "rpc Method(stream A) returns (stream B)":
	//   - A = what server RECEIVES (what client SENDS)
	//   - B = what server SENDS (what client RECEIVES)
	//
	// We want:
	//   - Server receives: CacheUpdate (from informers client)
	//   - Server sends: SyncMessage (requests/acks)
	//
	// Therefore we need: (stream CacheUpdate) returns (stream SyncMessage)
	StreamUpdates(grpc.BidiStreamingServer[CacheUpdate, SyncMessage]) error
	mustEmbedUnimplementedKubernetesCacheServiceServer()
}

// UnimplementedKubernetesCacheServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKubernetesCacheServiceServer struct{}

func (UnimplementedKubernetesCacheServiceServer) StreamUpdates(grpc.BidiStreamingServer[CacheUpdate, SyncMessage]) error {
	return status.Error(codes.Unimplemented, "method StreamUpdates not implemented")
}
func (UnimplementedKubernetesCacheServiceServer) mustEmbedUnimplementedKubernetesCacheServiceServer() {
}
func (UnimplementedKubernetesCacheServiceServer) testEmbeddedByValue() {}

// UnsafeKubernetesCacheServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KubernetesCacheServiceServer will
// result in compilation errors.
type UnsafeKubernetesCacheServiceServer interface {
	mustEmbedUnimplementedKubernetesCacheServiceServer()
}

func RegisterKubernetesCacheServiceServer(s grpc.ServiceRegistrar, srv KubernetesCacheServiceServer) {
	// If the following call panics, it indicates UnimplementedKubernetesCacheServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KubernetesCacheService_ServiceDesc, srv)
}

func _KubernetesCacheService_StreamUpdates_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(KubernetesCacheServiceServer).StreamUpdates(&grpc.GenericServerStream[CacheUpdate, SyncMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type KubernetesCacheService_StreamUpdatesServer = grpc.BidiStreamingServer[CacheUpdate, SyncMessage]

// KubernetesCacheService_ServiceDesc is the grpc.ServiceDesc for KubernetesCacheService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KubernetesCacheService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "k8scache.KubernetesCacheService",
	HandlerType: (*KubernetesCacheServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamUpdates",
			Handler:       _KubernetesCacheService_StreamUpdates_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/k8scache.proto",
}
