{
 "title": "Flow-Logs to Metrics - Totals",
 "tags": [
  "flp",
  "grafana",
  "dashboard",
  "total"
 ],
 "time": { "from": "now", "to": "now" },
 "panels": [
  {
   "title": "Connection length histogram",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "flp_connection_length_histogram_bucket{aggregate=\"endConnection\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Total bandwidth",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(flp_egress_per_destination_subnet[1m]))"
    }
   ]
  },
  {
   "title": "Flows length histogram",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "flp_flows_length_histogram_bucket",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Number of network services",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "count(flp_service_count)" }
   ]
  }
 ]
}