{
 "title": "Flow-Logs to Metrics - Details",
 "tags": [
  "flp",
  "grafana",
  "dashboard",
  "details"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Bandwidth per network service",
   "type": "graph",
   "gridPos": { "h": 20, "w": 25, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10,rate(flp_bandwidth_per_network_service[1m]))"
    }
   ]
  },
  {
   "title": "Bandwidth per src and destination subnet",
   "type": "graph",
   "gridPos": { "h": 20, "w": 25, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10,rate(flp_bandwidth_per_source_destination_subnet[1m]))"
    }
   ]
  },
  {
   "title": "Bandwidth per source subnet",
   "type": "graph",
   "gridPos": { "h": 20, "w": 25, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10,rate(flp_bandwidth_per_source_subnet[1m]))"
    }
   ]
  },
  {
   "title": "Connections rate per destinationIP /16 subnets",
   "type": "graph",
   "gridPos": { "h": 20, "w": 25, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10,rate(flp_connections_per_destination_subnet[1m]))"
    }
   ]
  },
  {
   "title": "Connections rate per sourceIP /16 subnets",
   "type": "graph",
   "gridPos": { "h": 20, "w": 25, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10,rate(flp_connections_per_source_subnet[1m]))"
    }
   ]
  },
  {
   "title": "Connections rate per TCPFlags",
   "type": "graph",
   "gridPos": { "h": 20, "w": 25, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10,rate(flp_connections_per_tcp_flags[1m]))"
    }
   ]
  },
  {
   "title": "Connections rate per destination AS",
   "type": "graph",
   "gridPos": { "h": 20, "w": 25, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10,rate(flp_connections_per_destination_as[1m]))"
    }
   ]
  },
  {
   "title": "Connections rate per source AS",
   "type": "graph",
   "gridPos": { "h": 20, "w": 25, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10,rate(flp_connections_per_source_as[1m]))"
    }
   ]
  },
  {
   "title": "Connections rate of src / destination subnet occurences",
   "type": "graph",
   "gridPos": { "h": 20, "w": 25, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10,rate(flp_count_per_source_destination_subnet[1m]))"
    }
   ]
  },
  {
   "title": "Bandwidth per destination subnet",
   "type": "graph",
   "gridPos": { "h": 20, "w": 25, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10,rate(flp_egress_per_destination_subnet[1m]))"
    }
   ]
  },
  {
   "title": "Bandwidth per namespace",
   "type": "graph",
   "gridPos": { "h": 20, "w": 25, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(flp_egress_per_namespace{aggregate=~\".*Pod.*\"}[1m])"
    }
   ]
  },
  {
   "title": "Connections rate per destinationIP geo-location",
   "type": "graph",
   "gridPos": { "h": 20, "w": 25, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10,rate(flp_connections_per_destination_location[1m]))"
    }
   ]
  },
  {
   "title": "Mice flows count",
   "type": "graph",
   "gridPos": { "h": 20, "w": 25, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(flp_mice_count{}[1m])" }
   ]
  },
  {
   "title": "Elephant flows count",
   "type": "graph",
   "gridPos": { "h": 20, "w": 25, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(flp_elephant_count{}[1m])" }
   ]
  },
  {
   "title": "Mice-elepahnts heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 25, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(flp_mice_elephants_histogram_bucket[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Network services connections rate",
   "type": "graph",
   "gridPos": { "h": 20, "w": 25, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10,rate(flp_service_count[1m]))"
    }
   ]
  }
 ]
}