apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: flp
  labels:
    k8s-app: flp
spec:
  selector:
    matchLabels:
      k8s-app: flp
  template:
    metadata:
      labels:
        k8s-app: flp
    spec:
      serviceAccountName: ebpf-agent-test
      containers:
        - name: flp
          image: quay.io/praveingk/flowlogs-pipeline:latest
          ports:
            - containerPort: 9999
              hostPort: 9999
          args:
            - --config=/etc/flp/config.yaml
          volumeMounts:
            - mountPath: /etc/flp
              name: config-volume
      volumes:
        - name: config-volume
          configMap:
            name: flp-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: flp-config
data:
  config.yaml: |
    log-level: debug
    pipeline:
      - name: ingest
      - name: enrich
        follows: ingest
      - name: loki
        follows: enrich
    parameters:
      - name: ingest
        ingest:
          type: grpc
          grpc:
            port: 9999
      - name: enrich
        transform:
          type: network
          network:
            rules:
              - input: SrcAddr
                output: SrcK8S
                type: "add_kubernetes"
              - input: DstAddr
                output: DstK8S
                type: "add_kubernetes"
      - name: write_ipfix
        write:
          type: ipfix
          ipfix:
            targetHost: 127.0.0.1
            targetPort: 9998
            transport: tcp