apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/netobserv/flowlogs-pipeline?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: |
      event == "pull_request" && target_branch == "main" && (
        ".tekton/***".pathChanged() ||
        ".dockerignore".pathChanged() ||
        "contrib/docker/Dockerfile.downstream".pathChanged() ||
        "contrib/docker/Dockerfile-args.downstream".pathChanged() ||
        "go.mod".pathChanged() ||
        "go.sum".pathChanged() ||
        "cmd/***".pathChanged() ||
        "pkg/***".pathChanged() ||
        "Makefile".pathChanged() ||
        "LICENSE".pathChanged()
      )
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: netobserv-ystream
    appstudio.openshift.io/component: flowlogs-pipeline-ystream
    pipelines.appstudio.openshift.io/type: build
  name: flowlogs-pipeline-ystream-on-pull-request
  namespace: ocp-network-observab-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/ocp-network-observab-tenant/flowlogs-pipeline-ystream:on-pr-{{revision}}
  - name: image-expires-after
    value: 5d
  - name: build-args-file
    value: contrib/docker/Dockerfile-args.downstream
  - name: dockerfile
    value: contrib/docker/Dockerfile.downstream
  - name: build-platforms
    value:
    - linux/x86_64
  pipelineRef:
    name: build-pipeline
  taskRunTemplate:
    serviceAccountName: build-pipeline-flowlogs-pipeline-ystream
status: {}
