log-level: debug
pipeline:
  - name: ingest1
  - name: generic1
    follows: ingest1
  - name: write1
    follows: generic1
parameters:
  - name: ingest1
    ingest:
      type: file
      file:
        filename: playground/goflow2_input.txt
        decoder:
          type: json
  - name: generic1
    transform:
      type: generic
      generic:
        policy: replace_keys
        rules:
          - input: Bytes
            output: flp_bytes
          - input: DstAddr
            output: flp_dstAddr
          - input: DstHostIP
            output: flp_dstHostIP
          - input: DstPort
            output: flp_dstPort
          - input: Packets
            output: flp_packets
          - input: SrcAddr
            output: flp_srcAddr
          - input: SrcHostIP
            output: flp_srcHostIP
          - input: SrcPort
            output: flp_srcPort
          - input: TimeReceived
            output: flp_timestamp
  - name: write1
    write:
      type: stdout

