log-level: debug
pipeline:
  ingest:
    type: kafka
    kafka:
      brokers: ["192.168.56.103:9092"]
      topic: topic1
      groupid: group1
  decode:
    type: json
  transform:
    - type: none
  extract:
    type: none
  encode:
    type: none
  write:
    type: stdout

